export const FETCH_NOTIFICATIONS = 'READ_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';
export const MARK_NOTIFICATION_AS_SEEN = 'MARK_NOTIFICATION_AS_SEEN';
export const REMOVE_NOTIFICATIONS = 'REMOVE_NOTIFICATIONS';
