export const SET_USERS = 'SET_USERS';
export const CLEAR_AUTH_USER = 'CLEAR_AUTH_USER';
export const SET_AUTH_USER_INFO = 'SET_AUTH_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const SET_FIREBASE_MESSAGING_TOKEN = 'SET_FIREBASE_MESSAGING_TOKEN';
export const SET_XP = 'SET_XP';
