import Topic from '~/constants/topicType';
import Reward from '~/constants/rewardType';
import { Card } from '~/constants/cardFields';
import ActivitySubmission from '~/constants/activitySubmissionType';
import HelpRequest from '~/constants/HelpRequestType';
import { CardActionTypes } from './types';
export declare function receivePlaces(options: any): CardActionTypes;
export declare function setCards(options: Card[]): CardActionTypes;
export declare function setHelpRequests(options: HelpRequest[]): CardActionTypes;
export declare function setCardTemplate(options: Card): CardActionTypes;
export declare function receiveRewards(options: Reward[]): CardActionTypes;
export declare function deleteReward(options: string): CardActionTypes;
export declare function putReward(options: Reward): CardActionTypes;
export declare function receiveCollectibleCards(options: Card[]): CardActionTypes;
export declare function receiveCreatedCards(options: Card[]): CardActionTypes;
export declare function updateCard(options: Card): CardActionTypes;
export declare function removeActivitySub(options: {
    id: string;
    uid: string;
}): CardActionTypes;
export declare function updateCardSuccess(): CardActionTypes;
export declare function updateCardError(): CardActionTypes;
export declare function createCard(options: Card): CardActionTypes;
export declare function seeCard(options: string): CardActionTypes;
export declare function createCardSuccess(): CardActionTypes;
export declare function createCardError(): CardActionTypes;
export declare function deleteCard(options: string): CardActionTypes;
export declare function deleteCardSuccess(): CardActionTypes;
export declare function deleteCardError(): CardActionTypes;
export declare function updateCardTemplate(options: Card): CardActionTypes;
export declare function submitActivity(options: ActivitySubmission): CardActionTypes;
export declare function submitActivitySuccess(): CardActionTypes;
export declare function deleteTopic(options: string): CardActionTypes;
export declare function receiveTopics(options: Topic[]): CardActionTypes;
export declare function putTopic(options: Topic): CardActionTypes;
